SELECT * FROM TAB;

CREATE TABLE ITEM_DETAIL (
	ITEM_ID INT PRIMARY KEY,
	DETAIL VARCHAR2(200)
);

CREATE TABLE ITEM (
	ITEM_ID INT PRIMARY KEY,
	NAME VARCHAR2(100)
);

DELETE FROM MEMBER_HISTORY

SELECT * FROM MEMBER_HISTORY

INSERT INTO MEMBER_HISTORY
VALUES ('madvirus', '2015스프링4프로그래밍입문<br>' || '2013 Spring4.0프로그래밍<br>'
|| '2012 객체지향과 디자인 패턴<br>' || '2012 JSP 2.2웹프로그래밍');

CREATE TABLE MEMBER_HISTORY (
MEMBERID VARCHAR2(10) PRIMARY KEY,
HISTORY VARCHAR2(250) 
)

SELECT * FROM MEMBER

INSERT INTO MEMBER(MEMBERID, PASSWORD, NAME, EMAIL)
VALUES ('eral3','5678','최범균', 'madvirus@madvirus.net')

INSERT INTO MEMBER(MEMBERID, PASSWORD, NAME)
VALUES ('madvirus','1234','최범균')

CREATE TABLE MEMBER (
	MEMBERID VARCHAR2(10) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR2(10) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(80)
)